name: sublime_dart_plugin_tools
version: 0.0.1
description: A minimal command-line application.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  path: '>=1.0.0 <2.0.0'
  # yaml: '>=1.0.0 <2.0.0'
  glob: any
dev_dependencies:
  unittest: any
